### PR TITLE
Move digest.rb back under ext as the extension bundled library

### PR DESCRIPTION
**Pull request by nobu**

### CODE REVIEW

**Comment by knu** [comment]
You should have waited for #20 before doing this because it causes a conflict.

**Comment by hsbt** [comment]
And I'm not sure why we leave from the standard gem layout with this changes.

**Comment by knu** [comment]
My plan is to have platform independent parts in lib/digest.rb and platform specific parts in ext, one for CRuby and another for JRuby.
https://github.com/ruby/digest/pull/21#issuecomment-913697693

**Comment by hsbt** [comment]
@knu I agreed that.

**Pull request merged**
