### PR TITLE
CI: Add "3.0" to matrix, and bump gem version to "3.0.1.pre" to differentiate from built-in

### PR DESCRIPTION
**Pull request by olleolleolle**

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Re the Ruby (Windows) master failures, if I change the version here to `3.1.0` or `3.0.1.pre`, it builds and installs (using `pkg/*.gem`) fine.

Seems like a RubyGems issue?  If I install digest, it acts like it's installing `digest:3.0.0`, but it doesn't do anything, as the version matches the default gem...  Not sure...

Maybe a Ubuntu master/head build should be added to CI also?

**Comment by olleolleolle** [comment]
@MSP-Greg 👋 Good idea, I added a Ubuntu20+head as an extra element.

**Comment by MSP-Greg** [comment]
@olleolleolle

Thanks.  I knew it was not a Windows issue, but a Ruby master/head issue.  People tend to always assume Windows issues are OS specific.  The 'debug' builds are master/head builds.

So, the solution (for now) might be to increment the version?

**Comment by olleolleolle** [comment]
@MSP-Greg Do you mean "increment the version of this gem"?

**Comment by MSP-Greg** [comment]
@olleolleolle

> Do you mean "increment the version of this gem"?

Yes.

Sorry, too much multi tasking this morning...  I think the issue that's confusing RubyGems is that with Ruby master/head, the default digest gem is also version `3.0.0`?

**Comment by olleolleolle** [comment]
@MSP-Greg In order to test that assumption, I made a change to the version directive in the gemspec of this gem, now, in this PR, to see if there is any change in results in the matrix.

**Review by mrkn — APPROVED** [review]
+1 Looks good to me.

**Pull request merged**
